Add `Ros2LocalizationClient`
openrr/openrr pull request #860
Opened 2023-09-13 03:41 UTC by kaaatsu32329

2023-09-14 12:38 UTC, taiki-e requested changes
- Could you update plugin.rs? (like [this](https://github.com/openrr/openrr/commit/196d7861973d4b9d42cc7c2d10a563f45d7a2ba7#diff-353541611e293847f166fd8d0225cd6932b6e707d1a35812bacd2944312e343d))
- Could you add a test for request_final_nomotion_update_hack=true case?
- ~~Could you add a comment on why request_final_nomotion_update_hack is considered a "hack" and why that is needed?~~

2023-09-19 02:44 UTC, taiki-e commented
LGTM, but you need to resolve conflicts.

2023-09-19 06:19 UTC, OTL commented
@taiki-e Please hijack this.

2023-09-21 04:10 UTC, taiki-e approved these changes

2023-09-21 04:11 UTC, merged